name: Python CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Running the job on the latest Ubuntu environment

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Check out your code so that the workflow can access it

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use the Python version required for your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt file
         
    - name: Run tests
      run: |
          pytest tests/
